//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PazarYeri.BusinessLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PazarYeri.BusinessLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS ( SELECT      1
        ///            FROM        sys.objects AS o
        ///            LEFT JOIN   sys.columns AS c WITH (NOLOCK) ON c.object_id = o.object_id
        ///            WHERE       o.name = @TableName
        ///                        AND o.type = &apos;U&apos;
        ///                        AND c.name = @NewColumnName)
        ///BEGIN
        ///
        ///  DECLARE @SQLTEXT NVARCHAR(1000)
        ///
        ///  SET @SQLTEXT = &apos;ALTER TABLE dbo.&apos; + @TableName + &apos; ADD &apos; + @NewColumnName + &apos; &apos; + @DataType + &apos; NULL&apos;
        ///
        ///  EXEC sys.sp_executesql @SQLTEXT
        ///
        ///END.
        /// </summary>
        internal static string AddColumn {
            get {
                return ResourceManager.GetString("AddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT   ISNULL(( SELECT     TOP 1   name
        ///                             FROM       master.sys.databases
        ///                             WHERE      name = @DatabaseName
        ///                             ORDER BY   database_id), &apos;&apos;))
        ///  SELECT    1
        ///ELSE
        ///  SELECT    0.
        /// </summary>
        internal static string checkDatabase {
            get {
                return ResourceManager.GetString("checkDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string checkTable {
            get {
                return ResourceManager.GetString("checkTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[net_EntegrationSettings]
        ///(
        ///  [Id] [INT] IDENTITY(1, 1) NOT NULL
        /// ,[EntegrationName] [NVARCHAR](50) NULL
        /// ,[FirmCode] [NVARCHAR](50) NULL
        /// ,[UserName] [NVARCHAR](50) NULL
        /// ,[PassWord] [NVARCHAR](250) NULL
        /// ,[Excel] [BIT] NULL
        /// ,[WebService] [BIT] NULL
        /// ,[Specode] [NVARCHAR](50) NULL
        /// ,[PaymentCode] [NVARCHAR](50) NULL
        /// ,[ArpCodeShpm] [NVARCHAR](50) NULL
        /// ,[ArpCode] [NVARCHAR](50) NULL
        ///) ON [PRIMARY]
        ///
        ///CREATE TABLE [dbo].[net_LogoSettings]
        ///(
        ///  [Id] [INT] IDENTITY(1, 1) NOT  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string createTables {
            get {
                return ResourceManager.GetString("createTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT      1
        ///            FROM        sys.objects AS o
        ///            LEFT JOIN   sys.columns AS c WITH (NOLOCK) ON c.object_id = o.object_id
        ///            WHERE       o.name = @TableName
        ///                        AND o.type = &apos;U&apos;
        ///                        AND c.name = @ColumnName)
        ///BEGIN
        ///
        ///  DECLARE @SQLTEXT NVARCHAR(1000)
        ///
        ///  SET @SQLTEXT = &apos;ALTER TABLE dbo.&apos; + @TableName + &apos; DROP COLUMN &apos; + @ColumnName
        ///
        ///  EXEC sys.sp_executesql @SQLTEXT
        ///
        ///END.
        /// </summary>
        internal static string DropColumn {
            get {
                return ResourceManager.GetString("DropColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  ISNULL(( SELECT TOP 1   CODE
        ///                 FROM   dbo.LG_001_CLCARD
        ///                 WHERE  TCKNO = @ID), &apos;&apos;).
        /// </summary>
        internal static string GetCLCodeByTCKN {
            get {
                return ResourceManager.GetString("GetCLCodeByTCKN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  ISNULL(( SELECT     TOP 1   CODE
        ///                 FROM       dbo.LG_001_CLCARD
        ///                 WHERE      DEFINITION2 = @DEFINITION2
        ///                 ORDER BY   LOGICALREF DESC), &apos;&apos;).
        /// </summary>
        internal static string GetClCodeByUserName {
            get {
                return ResourceManager.GetString("GetClCodeByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  ISNULL(( SELECT TOP 1   CODE
        ///                 FROM   dbo.LG_001_CLCARD
        ///                 WHERE  SPECODE5 = @ID), &apos;&apos;).
        /// </summary>
        internal static string GetClCodeByUyeId {
            get {
                return ResourceManager.GetString("GetClCodeByUyeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  ISNULL(( SELECT     TOP 1   ClientCode
        ///                 FROM       dbo.net_ClientPairing
        ///                 WHERE      EntegrationName = @EntegrationName
        ///                            AND EMail = @EMail
        ///                 ORDER BY   Id), &apos;&apos;).
        /// </summary>
        internal static string GetClientCodeFromPairingTable {
            get {
                return ResourceManager.GetString("GetClientCodeFromPairingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  *
        ///FROM    dbo.net_EntegrationSettings
        ///WHERE   EntegrationName = @entegrationName.
        /// </summary>
        internal static string GetEntegrationSettings {
            get {
                return ResourceManager.GetString("GetEntegrationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT      ITM.CODE
        ///           ,ITM.NAME
        ///           ,BRC.BARCODE
        ///FROM        dbo.LG_001_ITEMS AS ITM
        ///LEFT JOIN   dbo.LG_001_UNITBARCODE AS BRC ON BRC.ITEMREF = ITM.LOGICALREF
        ///                                             AND BRC.LINENR = 1
        ///WHERE       ITM.CARDTYPE &lt;&gt; 22.
        /// </summary>
        internal static string GetItemList {
            get {
                return ResourceManager.GetString("GetItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT      TOP 1   CONVERT(INT, CONVERT(FLOAT, T.CODE)) + 1
        ///FROM        ( SELECT    SUBSTRING(CODE, LEN(@PREFIX) + 1, 20) AS CODE
        ///              FROM      dbo.LG_001_CLCARD
        ///              WHERE     CODE LIKE @PREFIX + N&apos;%&apos;
        ///                        AND ISNUMERIC(SUBSTRING(CODE, LEN(@PREFIX) + 1, 20)) = 1) AS T
        ///ORDER BY    CONVERT(INT, CONVERT(FLOAT, T.CODE)) DESC.
        /// </summary>
        internal static string GetLastClCode {
            get {
                return ResourceManager.GetString("GetLastClCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  ISNULL(( SELECT     TOP 1   ITM.CODE
        ///                 FROM       dbo.LG_001_UNITBARCODE AS BAR
        ///                 LEFT JOIN  dbo.LG_001_ITEMS AS ITM WITH (NOLOCK) ON ITM.LOGICALREF = BAR.ITEMREF
        ///                 WHERE      BAR.BARCODE = @BARCODE
        ///                 ORDER BY   BAR.LOGICALREF DESC), &apos;&apos;).
        /// </summary>
        internal static string GetLogoItemCodeByBarcode {
            get {
                return ResourceManager.GetString("GetLogoItemCodeByBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  *
        ///FROM    dbo.net_LogoSettings.
        /// </summary>
        internal static string GetLogoSettings {
            get {
                return ResourceManager.GetString("GetLogoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  *
        ///FROM    dbo.net_LogoTransferSettings
        ///WHERE   EntegrationName = @entegrationName.
        /// </summary>
        internal static string GetLogoTransferSettings {
            get {
                return ResourceManager.GetString("GetLogoTransferSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  ISNULL(( SELECT     TOP 1   NETTOTAL
        ///                 FROM       dbo.LG_001_01_ORFICHE
        ///                 WHERE      LOGICALREF = @FICHEREF
        ///                 ORDER BY   LOGICALREF), 0).
        /// </summary>
        internal static string GetOrderAmount {
            get {
                return ResourceManager.GetString("GetOrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  *
        ///FROM    dbo.net_ProductPairing
        ///WHERE   EntegrationName = @EntegrationName
        ///        AND EntegrationCode = @EntegrationCode.
        /// </summary>
        internal static string GetProductPairing {
            get {
                return ResourceManager.GetString("GetProductPairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT      SHP.CODE AS Code
        ///           ,CLC.CODE AS ArpCode
        ///           ,SHP.NAME AS Description
        ///           ,SHP.ADDR1 AS Address1
        ///           ,SHP.ADDR2 AS Address2
        ///           ,SHP.CITY AS City
        ///           ,SHP.TOWN AS Town
        ///FROM        dbo.LG_001_SHIPINFO AS SHP
        ///LEFT JOIN   dbo.LG_001_CLCARD AS CLC WITH (NOLOCK) ON CLC.LOGICALREF = SHP.CLIENTREF
        ///WHERE       SHP.CODE = @SHIPCODE
        ///            AND CLC.CODE = @CLIENTCODE.
        /// </summary>
        internal static string GetShippingAddress {
            get {
                return ResourceManager.GetString("GetShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  ISNULL(( SELECT     TOP 1   ITM.VAT
        ///                 FROM       dbo.LG_001_ITEMS AS ITM
        ///                 WHERE      ITM.CODE = @ITEMCODE
        ///                 ORDER BY   ITM.LOGICALREF), 18).
        /// </summary>
        internal static string GetTaxRate {
            get {
                return ResourceManager.GetString("GetTaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT  TOP 1   ClientCode
        ///            FROM    dbo.net_ClientPairing
        ///            WHERE   EntegrationName = @EntegrationName
        ///                    AND EMail = @EMail)
        ///BEGIN
        ///
        ///  UPDATE    dbo.net_ClientPairing
        ///  SET       ClientCode = @ClientCode
        ///  WHERE     EntegrationName = @EntegrationName
        ///            AND EMail = @EMail
        ///
        ///END
        ///ELSE
        ///BEGIN
        ///
        ///  INSERT INTO   dbo.net_ClientPairing
        ///  (
        ///    LogoFirmNo
        ///   ,EntegrationName
        ///   ,EMail
        ///   ,ClientCode
        ///  )
        ///  VALUES
        ///  ( @LogoFirmNo
        ///   ,@Ent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertOrUpdateClientPairing {
            get {
                return ResourceManager.GetString("InsertOrUpdateClientPairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT  1
        ///            FROM    dbo.net_EntegrationSettings
        ///            WHERE   Id = @Id)
        ///BEGIN
        ///  UPDATE    dbo.net_EntegrationSettings
        ///  SET       EntegrationName = @EntegrationName
        ///           ,FirmCode = @FirmCode
        ///           ,UserName = @UserName
        ///           ,PassWord = @PassWord
        ///           ,Excel = @Excel
        ///           ,WebService = @WebService
        ///  WHERE     Id = @Id
        ///END
        ///ELSE
        ///BEGIN
        ///  INSERT INTO   dbo.net_EntegrationSettings
        ///  (
        ///    EntegrationName
        ///   ,FirmCode
        ///   ,UserName
        ///   ,Pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string saveEntegrationSettings {
            get {
                return ResourceManager.GetString("saveEntegrationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS ( SELECT  1
        ///                FROM    dbo.net_Orders
        ///                WHERE   EntegrationName = @EntegrationName
        ///                        AND OrderNo = @OrderNo
        ///                        AND LineNr = @LineNr)
        ///BEGIN
        ///  INSERT INTO   dbo.net_Orders
        ///  (
        ///    EntegrationName
        ///   ,OrderNo
        ///   ,OrderDate
        ///   ,OrderXml
        ///   ,Transfered
        ///   ,ResultMsg
        ///   ,LineNr
        ///  )
        ///  VALUES
        ///  ( @EntegrationName
        ///   ,@OrderNo
        ///   ,@OrderDate
        ///   ,@OrderXml
        ///   ,@Transfered
        ///   ,@ResultMsg
        ///   ,@LineNr)
        ///END.
        /// </summary>
        internal static string saveKoctasOrders {
            get {
                return ResourceManager.GetString("saveKoctasOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT  1
        ///            FROM    dbo.net_LogoSettings)
        ///BEGIN
        ///  UPDATE    dbo.net_LogoSettings
        ///  SET       LogoServerName = @LogoServerName
        ///           ,LogoDatabase = @LogoDatabase
        ///           ,LogoUserName = @LogoUserName
        ///           ,LogoPassword = @LogoPassword
        ///           ,FirmNr = @FirmNr
        ///           ,PeriodNr = @PeriodNr
        ///           ,AutoTransfer = @AutoTransfer
        ///END
        ///ELSE
        ///BEGIN
        ///  INSERT INTO   dbo.net_LogoSettings
        ///  (
        ///    LogoServerName
        ///   ,LogoDatabase
        ///   ,LogoUserName
        ///   ,LogoPa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string saveLogoSettings {
            get {
                return ResourceManager.GetString("saveLogoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT  1
        ///            FROM    dbo.net_LogoTransferSettings
        ///            WHERE   EntegrationName = @EntegrationName)
        ///BEGIN
        ///
        ///  UPDATE    dbo.net_LogoTransferSettings
        ///  SET       ClientTransferPrefixCode = @ClientTransferPrefixCode
        ///           ,ClientTransferSpeCode1 = @ClientTransferSpeCode1
        ///           ,ClientTransferSpeCode2 = @ClientTransferSpeCode2
        ///           ,ClientTransferSpeCode3 = @ClientTransferSpeCode3
        ///           ,ClientTransferSpeCode4 = @ClientTransferSpeCode4
        ///           ,Clien [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string saveLogoTransferSettings {
            get {
                return ResourceManager.GetString("saveLogoTransferSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT  1
        ///            FROM    dbo.net_Orders
        ///            WHERE   EntegrationName = @EntegrationName
        ///                    AND OrderNo = @OrderNo
        ///                    AND LineNr = @LineNr)
        ///BEGIN
        ///  UPDATE    dbo.net_Orders
        ///  SET       EntegrationName = @EntegrationName
        ///           ,OrderNo = @OrderNo
        ///           ,OrderDate = @OrderDate
        ///           ,OrderXml = @OrderXml
        ///           ,ResultMsg = @ResultMsg
        ///           ,LineNr = @LineNr
        ///  WHERE     EntegrationName = @EntegrationName
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string saveOrders {
            get {
                return ResourceManager.GetString("saveOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT  1
        ///            FROM    dbo.net_ProductPairing
        ///            WHERE   Id = @Id)
        ///BEGIN
        ///  UPDATE    dbo.net_ProductPairing
        ///  SET       EntegrationName = @EntegrationName
        ///           ,EntegrationCode = @EntegrationCode
        ///           ,LogoCode = @LogoCode
        ///           ,Barcode = @Barcode
        ///  WHERE     Id = @Id
        ///END
        ///ELSE
        ///BEGIN
        ///  INSERT INTO   dbo.net_ProductPairing
        ///  (
        ///    EntegrationName
        ///   ,EntegrationCode
        ///   ,LogoCode
        ///   ,Barcode
        ///  )
        ///  VALUES
        ///  ( @EntegrationName
        ///   ,@EntegrationCo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string saveProductPairing {
            get {
                return ResourceManager.GetString("saveProductPairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT      1
        ///            FROM        sys.objects AS o
        ///            LEFT JOIN   sys.columns AS c WITH (NOLOCK) ON c.object_id = o.object_id
        ///            WHERE       o.name = @TableName
        ///                        AND o.type = &apos;U&apos;
        ///                        AND c.name = @OldColumnName)
        ///BEGIN
        ///
        ///  DECLARE @ObjectName NVARCHAR(100)
        ///  SET @ObjectName = @TableName + &apos;.&apos; + @OldColumnName
        ///
        ///  EXEC sys.sp_rename @objname = @ObjectName
        ///                    ,@newname = @NewColumnName
        ///                    , [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateColumns {
            get {
                return ResourceManager.GetString("UpdateColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT  1
        ///            FROM    dbo.net_Orders
        ///            WHERE   EntegrationName = @EntegrationName
        ///                    AND OrderNo = @OrderNo
        ///                    AND ( LineNr = @LineNr
        ///                          OR LineNr = -1))
        ///BEGIN
        ///  UPDATE    dbo.net_Orders
        ///  SET       EntegrationName = @EntegrationName
        ///           ,OrderNo = @OrderNo
        ///           ,OrderDate = @OrderDate
        ///           ,OrderXml = @OrderXml
        ///           ,ResultMsg = @ResultMsg
        ///           ,Transfered = @Transfered
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateOrders {
            get {
                return ResourceManager.GetString("UpdateOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE  dbo.net_Orders
        ///SET     Transfered = @IsTransfered
        ///WHERE   EntegrationName = @EntegrationName
        ///        AND OrderNo = @OrderNo.
        /// </summary>
        internal static string UpdateTransferedSign {
            get {
                return ResourceManager.GetString("UpdateTransferedSign", resourceCulture);
            }
        }
    }
}
