//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PazarYeri.BusinessLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://b2b.hepsiburada.com/services/orders3rdPartyNew.asmx")]
        public string PazarYeri_BusinessLayer_com_hepsiburada_b2b_orders3rdParty {
            get {
                return ((string)(this["PazarYeri_BusinessLayer_com_hepsiburada_b2b_orders3rdParty"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://81.8.87.101:8080/vediFileTransferWS/services/vediFileTransferWS/")]
        public string PazarYeri_BusinessLayer_koctas_com_tr_vediFileTransferWS {
            get {
                return ((string)(this["PazarYeri_BusinessLayer_koctas_com_tr_vediFileTransferWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.n11.com/ws/orderService/")]
        public string PazarYeri_BusinessLayer_com_n11_api_OrderServicePortService {
            get {
                return ((string)(this["PazarYeri_BusinessLayer_com_n11_api_OrderServicePortService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vsrm.koctas.com.tr/vediFileTransferWS/services/vediFileTransferWS/")]
        public string PazarYeri_BusinessLayer_tr_com_koctas_vsrm_vediFileTransferWS {
            get {
                return ((string)(this["PazarYeri_BusinessLayer_tr_com_koctas_vsrm_vediFileTransferWS"]));
            }
        }
    }
}
