//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PazarYeri.BusinessLayer.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.orders3rdPartyNewSoap")]
    public interface orders3rdPartyNewSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOpenOrders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfGetInvoiceOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfCreateInvoiceOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfSplitOrderOutput))]
        PazarYeri.BusinessLayer.ServiceReference2.ThirdPartySasForWebService[] GetOpenOrders(string SupplierCode, string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOpenOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<PazarYeri.BusinessLayer.ServiceReference2.ThirdPartySasForWebService[]> GetOpenOrdersAsync(string SupplierCode, string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOpenOrders_WithDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfGetInvoiceOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfCreateInvoiceOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfSplitOrderOutput))]
        PazarYeri.BusinessLayer.ServiceReference2.ThirdPartySasForWebService[] GetOpenOrders_WithDate(string SupplierCode, string UserName, string Password, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOpenOrders_WithDate", ReplyAction="*")]
        System.Threading.Tasks.Task<PazarYeri.BusinessLayer.ServiceReference2.ThirdPartySasForWebService[]> GetOpenOrders_WithDateAsync(string SupplierCode, string UserName, string Password, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOpenOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfGetInvoiceOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfCreateInvoiceOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfSplitOrderOutput))]
        PazarYeri.BusinessLayer.ServiceReference2.ThirdPartySasForWebService GetOpenOrder(string SupplierCode, string UserName, string Password, string SasNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOpenOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<PazarYeri.BusinessLayer.ServiceReference2.ThirdPartySasForWebService> GetOpenOrderAsync(string SupplierCode, string UserName, string Password, string SasNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SplitOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfGetInvoiceOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfCreateInvoiceOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfSplitOrderOutput))]
        PazarYeri.BusinessLayer.ServiceReference2.SplitOrderOutput SplitOrder(string SupplierCode, string UserName, string Password, PazarYeri.BusinessLayer.ServiceReference2.SplitOrderInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SplitOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<PazarYeri.BusinessLayer.ServiceReference2.SplitOrderOutput> SplitOrderAsync(string SupplierCode, string UserName, string Password, PazarYeri.BusinessLayer.ServiceReference2.SplitOrderInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfGetInvoiceOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfCreateInvoiceOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfSplitOrderOutput))]
        PazarYeri.BusinessLayer.ServiceReference2.CreateInvoiceOutput CreateInvoice(string SupplierCode, string UserName, string Password, PazarYeri.BusinessLayer.ServiceReference2.CreateInvoiceInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<PazarYeri.BusinessLayer.ServiceReference2.CreateInvoiceOutput> CreateInvoiceAsync(string SupplierCode, string UserName, string Password, PazarYeri.BusinessLayer.ServiceReference2.CreateInvoiceInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfGetInvoiceOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfCreateInvoiceOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutputBaseOfSplitOrderOutput))]
        PazarYeri.BusinessLayer.ServiceReference2.GetInvoiceOutput GetInvoice(string SupplierCode, string UserName, string Password, PazarYeri.BusinessLayer.ServiceReference2.GetInvoiceInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<PazarYeri.BusinessLayer.ServiceReference2.GetInvoiceOutput> GetInvoiceAsync(string SupplierCode, string UserName, string Password, PazarYeri.BusinessLayer.ServiceReference2.GetInvoiceInput input);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ThirdPartySasForWebService : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ThirdPartySasResult sasResultField;
        
        private string dateField;
        
        private string orderNoField;
        
        private string sasNoField;
        
        private string addressField;
        
        private ThirdPartySasItem[] sasItemListField;
        
        private string receiverNameField;
        
        private AddressInfo addressInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ThirdPartySasResult SasResult {
            get {
                return this.sasResultField;
            }
            set {
                this.sasResultField = value;
                this.RaisePropertyChanged("SasResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("OrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SasNo {
            get {
                return this.sasNoField;
            }
            set {
                this.sasNoField = value;
                this.RaisePropertyChanged("SasNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public ThirdPartySasItem[] SasItemList {
            get {
                return this.sasItemListField;
            }
            set {
                this.sasItemListField = value;
                this.RaisePropertyChanged("SasItemList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ReceiverName {
            get {
                return this.receiverNameField;
            }
            set {
                this.receiverNameField = value;
                this.RaisePropertyChanged("ReceiverName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public AddressInfo AddressInfo {
            get {
                return this.addressInfoField;
            }
            set {
                this.addressInfoField = value;
                this.RaisePropertyChanged("AddressInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ThirdPartySasResult {
        
        /// <remarks/>
        Gonderildi,
        
        /// <remarks/>
        Ertelendi,
        
        /// <remarks/>
        Cevaplanmadı,
        
        /// <remarks/>
        TedarikciGonderemiyor,
        
        /// <remarks/>
        Iptal,
        
        /// <remarks/>
        BarkodYazdirildi,
        
        /// <remarks/>
        FaturaOlusturuldu,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ThirdPartySasItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuField;
        
        private string tedSkuField;
        
        private string barcodesField;
        
        private string adetField;
        
        private string productNameField;
        
        private string kalemNoField;
        
        private bool customerCancelRequestField;
        
        private string customerNoteField;
        
        private System.DateTime estimatedShipmentDateField;
        
        private decimal totalPriceWithoutTaxField;
        
        private string currencyStringField;
        
        private string taxRateField;
        
        private decimal faturaTutarField;
        
        private string faturaKurField;
        
        private string faturaTarihField;
        
        private string faturaNoField;
        
        private string cargoFirmField;
        
        private string cargoFirmTextField;
        
        private string seenField;
        
        private string selfBillingField;
        
        private string schItemField;
        
        private string[] serialNumberListField;
        
        private bool serialNumberRequiredField;
        
        private string definitionNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("Sku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TedSku {
            get {
                return this.tedSkuField;
            }
            set {
                this.tedSkuField = value;
                this.RaisePropertyChanged("TedSku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Barcodes {
            get {
                return this.barcodesField;
            }
            set {
                this.barcodesField = value;
                this.RaisePropertyChanged("Barcodes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Adet {
            get {
                return this.adetField;
            }
            set {
                this.adetField = value;
                this.RaisePropertyChanged("Adet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string KalemNo {
            get {
                return this.kalemNoField;
            }
            set {
                this.kalemNoField = value;
                this.RaisePropertyChanged("KalemNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool CustomerCancelRequest {
            get {
                return this.customerCancelRequestField;
            }
            set {
                this.customerCancelRequestField = value;
                this.RaisePropertyChanged("CustomerCancelRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CustomerNote {
            get {
                return this.customerNoteField;
            }
            set {
                this.customerNoteField = value;
                this.RaisePropertyChanged("CustomerNote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime EstimatedShipmentDate {
            get {
                return this.estimatedShipmentDateField;
            }
            set {
                this.estimatedShipmentDateField = value;
                this.RaisePropertyChanged("EstimatedShipmentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal TotalPriceWithoutTax {
            get {
                return this.totalPriceWithoutTaxField;
            }
            set {
                this.totalPriceWithoutTaxField = value;
                this.RaisePropertyChanged("TotalPriceWithoutTax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CurrencyString {
            get {
                return this.currencyStringField;
            }
            set {
                this.currencyStringField = value;
                this.RaisePropertyChanged("CurrencyString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string TaxRate {
            get {
                return this.taxRateField;
            }
            set {
                this.taxRateField = value;
                this.RaisePropertyChanged("TaxRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal FaturaTutar {
            get {
                return this.faturaTutarField;
            }
            set {
                this.faturaTutarField = value;
                this.RaisePropertyChanged("FaturaTutar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FaturaKur {
            get {
                return this.faturaKurField;
            }
            set {
                this.faturaKurField = value;
                this.RaisePropertyChanged("FaturaKur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FaturaTarih {
            get {
                return this.faturaTarihField;
            }
            set {
                this.faturaTarihField = value;
                this.RaisePropertyChanged("FaturaTarih");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string FaturaNo {
            get {
                return this.faturaNoField;
            }
            set {
                this.faturaNoField = value;
                this.RaisePropertyChanged("FaturaNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CargoFirm {
            get {
                return this.cargoFirmField;
            }
            set {
                this.cargoFirmField = value;
                this.RaisePropertyChanged("CargoFirm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string CargoFirmText {
            get {
                return this.cargoFirmTextField;
            }
            set {
                this.cargoFirmTextField = value;
                this.RaisePropertyChanged("CargoFirmText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Seen {
            get {
                return this.seenField;
            }
            set {
                this.seenField = value;
                this.RaisePropertyChanged("Seen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string SelfBilling {
            get {
                return this.selfBillingField;
            }
            set {
                this.selfBillingField = value;
                this.RaisePropertyChanged("SelfBilling");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string SchItem {
            get {
                return this.schItemField;
            }
            set {
                this.schItemField = value;
                this.RaisePropertyChanged("SchItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=21)]
        public string[] SerialNumberList {
            get {
                return this.serialNumberListField;
            }
            set {
                this.serialNumberListField = value;
                this.RaisePropertyChanged("SerialNumberList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool SerialNumberRequired {
            get {
                return this.serialNumberRequiredField;
            }
            set {
                this.serialNumberRequiredField = value;
                this.RaisePropertyChanged("SerialNumberRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string DefinitionName {
            get {
                return this.definitionNameField;
            }
            set {
                this.definitionNameField = value;
                this.RaisePropertyChanged("DefinitionName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetInvoiceOutput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class OutputBaseOfGetInvoiceOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInvoiceOutput : OutputBaseOfGetInvoiceOutput {
        
        private byte[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInvoiceInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ticketIdField;
        
        private string sasNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TicketId {
            get {
                return this.ticketIdField;
            }
            set {
                this.ticketIdField = value;
                this.RaisePropertyChanged("TicketId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SasNo {
            get {
                return this.sasNoField;
            }
            set {
                this.sasNoField = value;
                this.RaisePropertyChanged("SasNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateInvoiceOutput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class OutputBaseOfCreateInvoiceOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateInvoiceOutput : OutputBaseOfCreateInvoiceOutput {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateInvoiceInputItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lineNoField;
        
        private string[] serialNumbersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LineNo {
            get {
                return this.lineNoField;
            }
            set {
                this.lineNoField = value;
                this.RaisePropertyChanged("LineNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] SerialNumbers {
            get {
                return this.serialNumbersField;
            }
            set {
                this.serialNumbersField = value;
                this.RaisePropertyChanged("SerialNumbers");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateInvoiceInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sasNoField;
        
        private CreateInvoiceInputItem[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SasNo {
            get {
                return this.sasNoField;
            }
            set {
                this.sasNoField = value;
                this.RaisePropertyChanged("SasNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public CreateInvoiceInputItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SplitOrderOutput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class OutputBaseOfSplitOrderOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SplitOrderOutput : OutputBaseOfSplitOrderOutput {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SplitOrderInputItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lineNoField;
        
        private string quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LineNo {
            get {
                return this.lineNoField;
            }
            set {
                this.lineNoField = value;
                this.RaisePropertyChanged("LineNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SplitOrderInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sourceSasNoField;
        
        private string detailsField;
        
        private SplitOrderInputItem[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SourceSasNo {
            get {
                return this.sourceSasNoField;
            }
            set {
                this.sourceSasNoField = value;
                this.RaisePropertyChanged("SourceSasNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("Details");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public SplitOrderInputItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AddressInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string isimField;
        
        private string adres1Field;
        
        private string adres2Field;
        
        private string adres3Field;
        
        private string cityField;
        
        private string districtField;
        
        private string townField;
        
        private string countryField;
        
        private string telgonderenField;
        
        private string telteslimalanField;
        
        private string isimgonderenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string isim {
            get {
                return this.isimField;
            }
            set {
                this.isimField = value;
                this.RaisePropertyChanged("isim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string adres1 {
            get {
                return this.adres1Field;
            }
            set {
                this.adres1Field = value;
                this.RaisePropertyChanged("adres1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string adres2 {
            get {
                return this.adres2Field;
            }
            set {
                this.adres2Field = value;
                this.RaisePropertyChanged("adres2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string adres3 {
            get {
                return this.adres3Field;
            }
            set {
                this.adres3Field = value;
                this.RaisePropertyChanged("adres3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("district");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
                this.RaisePropertyChanged("town");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string telgonderen {
            get {
                return this.telgonderenField;
            }
            set {
                this.telgonderenField = value;
                this.RaisePropertyChanged("telgonderen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string telteslimalan {
            get {
                return this.telteslimalanField;
            }
            set {
                this.telteslimalanField = value;
                this.RaisePropertyChanged("telteslimalan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string isimgonderen {
            get {
                return this.isimgonderenField;
            }
            set {
                this.isimgonderenField = value;
                this.RaisePropertyChanged("isimgonderen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface orders3rdPartyNewSoapChannel : PazarYeri.BusinessLayer.ServiceReference2.orders3rdPartyNewSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class orders3rdPartyNewSoapClient : System.ServiceModel.ClientBase<PazarYeri.BusinessLayer.ServiceReference2.orders3rdPartyNewSoap>, PazarYeri.BusinessLayer.ServiceReference2.orders3rdPartyNewSoap {
        
        public orders3rdPartyNewSoapClient() {
        }
        
        public orders3rdPartyNewSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public orders3rdPartyNewSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public orders3rdPartyNewSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public orders3rdPartyNewSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PazarYeri.BusinessLayer.ServiceReference2.ThirdPartySasForWebService[] GetOpenOrders(string SupplierCode, string UserName, string Password) {
            return base.Channel.GetOpenOrders(SupplierCode, UserName, Password);
        }
        
        public System.Threading.Tasks.Task<PazarYeri.BusinessLayer.ServiceReference2.ThirdPartySasForWebService[]> GetOpenOrdersAsync(string SupplierCode, string UserName, string Password) {
            return base.Channel.GetOpenOrdersAsync(SupplierCode, UserName, Password);
        }
        
        public PazarYeri.BusinessLayer.ServiceReference2.ThirdPartySasForWebService[] GetOpenOrders_WithDate(string SupplierCode, string UserName, string Password, string fromDate, string toDate) {
            return base.Channel.GetOpenOrders_WithDate(SupplierCode, UserName, Password, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<PazarYeri.BusinessLayer.ServiceReference2.ThirdPartySasForWebService[]> GetOpenOrders_WithDateAsync(string SupplierCode, string UserName, string Password, string fromDate, string toDate) {
            return base.Channel.GetOpenOrders_WithDateAsync(SupplierCode, UserName, Password, fromDate, toDate);
        }
        
        public PazarYeri.BusinessLayer.ServiceReference2.ThirdPartySasForWebService GetOpenOrder(string SupplierCode, string UserName, string Password, string SasNo) {
            return base.Channel.GetOpenOrder(SupplierCode, UserName, Password, SasNo);
        }
        
        public System.Threading.Tasks.Task<PazarYeri.BusinessLayer.ServiceReference2.ThirdPartySasForWebService> GetOpenOrderAsync(string SupplierCode, string UserName, string Password, string SasNo) {
            return base.Channel.GetOpenOrderAsync(SupplierCode, UserName, Password, SasNo);
        }
        
        public PazarYeri.BusinessLayer.ServiceReference2.SplitOrderOutput SplitOrder(string SupplierCode, string UserName, string Password, PazarYeri.BusinessLayer.ServiceReference2.SplitOrderInput input) {
            return base.Channel.SplitOrder(SupplierCode, UserName, Password, input);
        }
        
        public System.Threading.Tasks.Task<PazarYeri.BusinessLayer.ServiceReference2.SplitOrderOutput> SplitOrderAsync(string SupplierCode, string UserName, string Password, PazarYeri.BusinessLayer.ServiceReference2.SplitOrderInput input) {
            return base.Channel.SplitOrderAsync(SupplierCode, UserName, Password, input);
        }
        
        public PazarYeri.BusinessLayer.ServiceReference2.CreateInvoiceOutput CreateInvoice(string SupplierCode, string UserName, string Password, PazarYeri.BusinessLayer.ServiceReference2.CreateInvoiceInput input) {
            return base.Channel.CreateInvoice(SupplierCode, UserName, Password, input);
        }
        
        public System.Threading.Tasks.Task<PazarYeri.BusinessLayer.ServiceReference2.CreateInvoiceOutput> CreateInvoiceAsync(string SupplierCode, string UserName, string Password, PazarYeri.BusinessLayer.ServiceReference2.CreateInvoiceInput input) {
            return base.Channel.CreateInvoiceAsync(SupplierCode, UserName, Password, input);
        }
        
        public PazarYeri.BusinessLayer.ServiceReference2.GetInvoiceOutput GetInvoice(string SupplierCode, string UserName, string Password, PazarYeri.BusinessLayer.ServiceReference2.GetInvoiceInput input) {
            return base.Channel.GetInvoice(SupplierCode, UserName, Password, input);
        }
        
        public System.Threading.Tasks.Task<PazarYeri.BusinessLayer.ServiceReference2.GetInvoiceOutput> GetInvoiceAsync(string SupplierCode, string UserName, string Password, PazarYeri.BusinessLayer.ServiceReference2.GetInvoiceInput input) {
            return base.Channel.GetInvoiceAsync(SupplierCode, UserName, Password, input);
        }
    }
}
