SELECT      TOP 1   CONVERT(INT, CONVERT(FLOAT, T.CODE)) + 1
FROM        ( SELECT    SUBSTRING(CODE, LEN(@PREFIX) + 1, 20) AS CODE
              FROM      dbo.LG_001_CLCARD
              WHERE     CODE LIKE @PREFIX + N'%'
                        AND ISNUMERIC(SUBSTRING(CODE, LEN(@PREFIX) + 1, 20)) = 1) AS T
ORDER BY    CONVERT(INT, CONVERT(FLOAT, T.CODE)) DESC